### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ghost** [Jakousa/Shakkitekoaly#1]
Latasin projektin ensin 17.11 klo 19.30 mutta huomattuani uuden, hyvin päivitetyn version,
latasin sen uudestaan 19.11 klo 9. Nyt kaipaamani asiat olivatkin jo tulleet: luokkien selkeämpi
jako omiin paketteihin, sekä ihmispelaajan mahdollisuus. Sekä monia muita pikku ominaisuuksia.

Aikatauluun nähden tekoäly on edennyt hyvin; ohjelma toimii, ja pääsee jo pelaamaan tekoälyä vastaan!
Koska aina voi laajentaa lisää, niin annan palautteen lopuksi ehdotuksen lisäominaisuuksista.

Kiva uusi odottamaton ominaisuus kertoo, kauanko kesti koneen siirron tekemisessä. Näytetty aika 
2895834438422ms kuitenkin vaikutti epäilyttävältä, mikä tosin johtuu siitä, että ajat
aikaLopussa ja aikaAlussa on plussattu eikä vähennetty. Olisiko ihmisystävällisempi näyttää aika sekunteina?

Askel todellisempaan shakkipeliin voisi halutessa olla, että peli näyttäisi kummankin pelaajan 
kohdalla paljonko aikaa on kulunut siihen asti. Tämä mahdollistaisi esimerkiksi pikapelin.

Pelin aloitusvaiheen tulostuksissa näkyy pientä ihmeellistä toimintaa:

Haluatko pelata? Y/N
Y
Haluatko aloittaa? Y/N
Y
Minkä tasoinen toinen pelaaja? 
 Suosittelen < 5       //kun tähän vastasi 3 niin tulostui ensin lauta ja syöte tuli näkyviin tuonne alas
trlqklrt0
ssssssss1
###### ##5

SSSSSSSS6
TRLQKLRT7
abcdefgh*
0                      //lisäksi tämä 0 tulostuu joka kerta enkä ymmärtänyt sen tarkoitusta.
Minkä haluat siirtää. esim. C5
3

Myös tällainen tulostusongelma tuli vastaan.

Haluatko pelata? Y/N
Y
Haluatko aloittaa? Y/N
Minkä tasoinen toinen pelaaja? 
 Suosittelen < 5
Y
trlqklrt0
3
ssssssss1
###### ##5

SSSSSSSS6
TRLQKLRT7
abcdefgh*
0

Nämä tulostusongelmat tosin tapahtuvat vain satunnaisesti. Jokaisen siirron jälkeen kuitenkin 0 tulostuu pelilaudan jälkeen.

Pelilauta on numeroitu alhaalta ylös 7,6,5,... Tämä ei kuitenkaan ole oikean shakkilaudan numerointi. Ymmärtääkseni näin on numeroitu siksi että pelin logiikka toimii näin. Kenties tämän voisi korjata kääntäjällä: laudan numeroisi samoin kuin oikean shakkilaudan, mutta joka kerralla antaessa siirron logiikalle, käännettäisiin saatu siirto niin että logiikka ymmärtää mitä on haluttu siirtää. Etenkin tottunut shakinpelaaja menee hämilleen nykyisestä numeroinnista.

Sitten lisäominaisuuksia varten ehdotuksia:
shakkipeliin liittyen: 
kaksoissiirto, linnoitukset, ohestalyönti (tosin erityisen vaikea toteuttaa), laudan numerointi. Sotilaan korottaminen? En testannut, mutta toivottavasti kuningas ei voi liikkua uhattuun ruutuun. Kuningas ei saa myöskään linnoittaa uhatun ruudun ylitse.

tekoälyyn liittyen: 
sotilaat hallitsisivat keskustaa (eli tekoäly suosisi etenkin avauksessa d- ja e-sotilaiden siirtämistä).
Alussa pyrittäisiin linnoittamaan piakkoin.
Ei liikaa saman nappulan peräkkäin siirtämistä. (esim tornin siksakkaamista).
Lähettipari yhdessä on parempi kuin ratsut (suljetussa asemassa tietenkin eri juttu).
Käytännössä 2 tornia on yhdessä parempi kuin kuningatar.

**Comment by Jakousa** [comment]
Kiitos että kävit läpi kaikenlaisia bugeja. Aloitin juuri korjaamaan niitä tämän viikon palautusta varten.
Harkitsen noita shakin hienompia ominaisuuksia kuten kaksoissiirto, ohestalyönti, tornitus siinä kun loppupuolella saan tekoälyä vähän rassattua, esim tornien siksakkaaminen on ärsyttävää vaikka onkin häviävälle pelaajalle "paras" vaihtoehto.
